config/routes.rb
Rails.application.routes.draw do
  root to: 'page#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  get '/test', to: 'test#show'
  resources :places
  resources :collections

  get '/search', to: 'posts#search'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  has_many :places

  validates :name, presence: true
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  belongs_to :city
  validates :name, :user_id, :city_id, presence: true
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true, uniqueness: true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :city

  validates :name, :address, :place_type, :description, :image_url, :city_id, presence: true

  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true, email: true
  validates :password, password_strength: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/collections_controller.rb
# frozen_string_literal:true

# Controller for managing collections
class CollectionsController < ApplicationController
  before_action :set_collection, only: %i[show edit update destroy]

  # GET /collections
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @collection = Collection.new(collection_params)

    if @collection.save
      redirect_to @collection, notice: 'Collection was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /collections/1
  def update
    if @collection.update(collection_params)
      redirect_to @collection, notice: 'Collection was successfully updated.', status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy!
    redirect_to collections_url, notice: 'Collection was successfully destroyed.', status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def collection_params
    params.require(:collection).permit(:name, :user_id, :city_id)
  end
end

app/controllers/concerns/authentication_check.rb
module AuthenticationCheck
  extend ActiveSupport::Concern
    
  def is_user_logged_in
    if current_user.nil?
      render json: { message: "No user is authenticated." },
             status: :unauthorized
    end
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  def index
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  #this method is not final. It only sets an example on how to call api using the Faraday gem
  def index
    response = GeoapifyClient.connection.get("/v2/places") do |req|
      req.params["categories"] = "commercial.shopping_mall"
      req.params["filter"] = "place:51ed56e07547c754c059a9b64027292a4040f00101f901a578020000000000c0020a"
      req.params["limit"] = 5
    end
  end

  private
    def place_params
      params.require(:place).permit(:name, :address, :place_type, :description, :rating, :image_url, :city_id)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  include AuthenticationCheck
  
  before_action :is_user_logged_in
  
  def show
    render json: { message: "If you see this, you're logged in!" },
           status: :ok
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  private

  def respond_with(resource, _opts = {})
    register_success && return if resource.persisted?

    register_failed resource
  end

  def register_success
    redirect_to root_path, notice: 'Signed up sucessfully.'
  end

  def register_failed(resource)
    print(resource.errors.full_messages)
    # here we need to throw an error
    # @error_message = resource.errors.full_messages.join(', ')
    render :new
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  respond_to :json

  def destroy
    @logged_in_user = current_user
    super
  end

  private

  def respond_with(resource, _opts = {})
    if !resource.id.nil?
      render json: { message: 'You are logged in.' }, status: :created
    else
      render json: { message: 'Authentication failed.' }, status: :unauthorized
    end
  end

  def respond_to_on_destroy
    log_out_success && return if @logged_in_user

    log_out_failure
  end

  def log_out_success
    render json: { message: 'You are logged out.' }, status: :ok
  end

  def log_out_failure
    render json: { message: 'Hmm nothing happened.' }, status: :unauthorized
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/views/collections/_collection.html.erb
<div id="<%= dom_id collection %>">
</div>

app/views/collections/_form.html.erb
<%= form_with(model: collection) do |form| %>
  <% if collection.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(collection.errors.count, "error") %> prohibited this collection from being saved:</h2>

      <ul>
        <% collection.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/collections/edit.html.erb
<h1>Editing collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Show this collection", @collection %> |
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Collections</h1>

<div id="collections">
  <% @collections.each do |collection| %>
    <%= render collection %>
    <p>
      <%= link_to "Show this collection", collection %>
    </p>
  <% end %>
</div>

<%= link_to "New collection", new_collection_path %>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render "form", collection: @collection %>

<br>

<div>
  <%= link_to "Back to collections", collections_path %>
</div>

app/views/collections/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @collection %>

<div>
  <%= link_to "Edit this collection", edit_collection_path(@collection) %> |
  <%= link_to "Back to collections", collections_path %>

  <%= button_to "Destroy this collection", @collection, method: :delete %>
</div>

app/views/landing_page/index.html.erb
<h1>Here will be search input</h1>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top">
  <div class="container-fluid">
      <a class="navbar-link" href="<%= root_path %>">TripTag</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation" style="background-color: #e3f2fd;">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-lg-0">
         <% if user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= collection_path %>">Collections</a>
        </li>
        <%end%>
      </ul>
      </form>
   <div class="d-flex justify-content-md-between justify-content-between-sm align-items-baseline">
  <% if user_signed_in? %>
    <p class="m-0 mr-2">Welcome, <strong><%= current_user.email %></strong>!</p>
    <div class="ms-md-2 ms-auto mt-2 mt-md-0">
      <%= button_to "Log Out", destroy_user_session_path, method: :delete, class: "btn btn-light"%>
    </div>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary" %>
    <%= link_to "Login", new_user_session_path, class: "btn btn-primary mx-2" %>
  <% end %>
</div>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRPracticum</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/page/index.html.erb
<!-- navbar -->
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <%= image_tag "logo-1.png", class:"rounded float-start" %>
    <div style="display: flex; gap: 10px;" class="justify-content-sm-center">
      <div>
        <%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary" %>
      </div>
      <div class="d-grid gap-2 d-sm-flex">
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-success" %>
      </div>
    </div>
  </div>
</nav> <!-- /navbar -->

<!-- search places -->
<body>
  <div style="margin-top: 70px">
    <div class="search-container">
      <h1 class="display-1 fw-bold mt-3">E</h1><p class="display-6 fw-bold mt-5">XPLORE</p>
    </div>
    <p class="display-6 text-center fw-bold">the best places in the world!</p>
  </div>
  <div class="search-container">
    <%= form_tag('/search', method: :get) do %>
      <%= text_field_tag(:key, nil, placeholder:'place to go, things to do...') %>
      <%# <i class="fa-solid fa-magnifying-glass"></i> %>
      <%= submit_tag("Search", class:"btn btn-outline-primary") %>
    <% end %>
  </div>
  <!-- Other content goes here -->
</body> <!-- /search places -->

<!-- footer-->
<footer class="bg-light text-lg-star fixed-bottom" style="background-color: gray; margin-top: 50px">
  <div class="p-3">
    <p id="copyright" class="mb-2">© 2024 TripTag. All rights reserved.</p>
  </div>
</footer>  <!-- /footer-->